version: "3.8"

networks:
  nodejs:
    driver: bridge

# Command в докер compose переопределяет CMD в Dockerfile
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-server
    hostname: server
    restart: unless-stopped
    environment:
      - NODE_ENV={MODE}
    ports:
      - "${SERVER_PORT}:8008"
    env_file:
      - .env
    networks:
      - nodejs
    command: npm run start:dev